global:
  message: Welcome to Global Microservice Environment!!
logging:
  level:
    root: INFO
eureka:
  client:
    service-url:
      defautltZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure: 
        includes: health, info, refresh
  endpoint:
    health:
      show-details: always
