global:
  message: Welcome to Order Service Dev Environment!!
server:
  port: 8082
message: Hello from Order Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_master
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
